#!/usr/bin/ruby

require "rubygems"
require "bundler/setup"
require "optparse"
require "timeout"
require "net/ssh"

options = {
  :host => "127.0.0.1",
  :username => "root",
  :key_path => "~/.ssh/id_rsa",
  :name => "unknown"
}

OptionParser.new do |opts|
  opts.on("--host HOST") { |host| options[:host] = host } 
  opts.on("--username USERNAME") { |username| options[:username] = username }
  opts.on("--key-path KEY_PATH") { |key_path| options[:key_path] = key_path }

  opts.on "--help" do
    puts opts
    exit 0
  end 
end.parse!

begin
  Timeout::timeout 30 do
    Net::SSH.start(options[:host], options[:username], :keys => [options[:key_path]], :keys_only => true) do |ssh|
      begin
        faulty = ssh.exec!("/usr/local/cassandra/bin/nodetool status | grep rack").lines.select { |line| line !~ /^UN/ }.map { |line| line.split(/\s+/).first(2).join(": ") }

        if faulty.size > 0
          puts "CASSANDRA CRITICAL - #{faulty.join(", ")}"
          exit 2
        else
          puts "CASSANDRA OK"
          exit 0
        end
      rescue => e
        puts "CASSANDRA CRITICAL - #{e.message}"
        exit 2
      end
    end
  end
rescue => e
  puts "CASSANDRA CRITICAL - #{e.message}"
  exit 2
end

