#!/usr/bin/ruby

require "rubygems"
require "bundler/setup"
require "optparse"
require "timeout"
require "net/ssh"

options = {
  :host => "127.0.0.1",
  :username => "root",
  :key_path => "~/.ssh/id_rsa",
  :name => "unknown"
}

OptionParser.new do |opts|
  opts.on("--host HOST") { |host| options[:host] = host } 
  opts.on("--username USERNAME") { |username| options[:username] = username }
  opts.on("--key-path KEY_PATH") { |key_path| options[:key_path] = key_path }

  opts.on "--help" do
    puts opts
    exit 0
  end 
end.parse!

begin
  Timeout::timeout 30 do
    Net::SSH.start(options[:host], options[:username], :keys => [options[:key_path]], :keys_only => true) do |ssh|
      begin
        output = ssh.exec!("echo stat | nc localhost 2181")

        role = output.lines.grep(/Mode:.*(follower|leader)/i)

        if role.empty?
          puts "ZOOKEEPER CRITICAL"
          exit 2
        else
          puts "ZOOKEEPER OK #{role.first}"
          exit 0
        end
      rescue => e
        puts "ZOOKEEPER CRITICAL - #{e.message}"
        exit 2
      end
    end
  end
rescue => e
  puts "ZOOKEEPER CRITICAL - #{e.message}"
  exit 2
end

